# Configuration for Gemma3 27B K-sweep with vector caching
# Uses cached vectors for faster repeated experiments

# Evaluation parameters
eval:
  # K values to evaluate
  k_values: [1, 2, 4, 8, 16, 32]
  
  # Output settings
  output_dir: ./eval_results
  output_file: gemma3_k_sweep_cache.json
  
  # Evaluation settings
  max_batches: null  # Use entire validation set (or subset of cache)
  temperature: 1.0
  
  # Batch size settings
  batch_size: 8
  max_generation_batch_size: 64
  dataloader_batch_size: 128
  vector_extraction_batch_size: 16
  dataloader_fwd_pass_batch_size: 16
  
  # Performance settings
  use_bf16: true
  
  # Sampling settings
  num_positions: 1
  max_val_samples: 1000
  
  # Bootstrap settings
  do_bootstrap: false  # Bootstrap disabled by default for speed
  
  # Caching ENABLED
  load_store: true
  cache_dir: vector_cache_gemma3

# Dataset configuration
dataset:
  activation_dir: "./data/SimpleStories_train"
  val_activation_dir: "./data/SimpleStories_test"
  
  on_the_fly:
    enabled: false
    generation_batch_size: 32

# Data loader settings
data:
  num_workers: 0