# Configuration for dataset pre-tokenization
defaults:
  - _self_
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# Pretokenization parameters
pretokenize:
  # Output directory for pretokenized datasets
  # If null, will use data/pretokenized/{dataset_name}
  output_dir: null
  
  # Number of processes for parallel tokenization
  num_proc: 32
  
  # Batch size for tokenization
  batch_size: 10000
  
  # Whether to force re-tokenization even if output exists
  force: false

# These will be inherited from the main config when using defaults
# But can be overridden here if needed
model_name: ${model_name}
tokenizer_name: ${tokenizer_name}
activation_dumper: ${activation_dumper}

# Hydra configuration
hydra:
  run:
    dir: outputs/pretokenize/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: pretokenize