# Configuration for GPT-2 Frozen Base Model Experiment
# This config trains consistency lens on GPT-2 with the base model frozen throughout

defaults:
  - config 
  - _self_

# Training hyperparameters
layer_l: 4
t_text: 8                       # Number of tokens to generate with the Decoder
decoder_prompt: "[EOS]Short explanation of <embed>. Topic, speaker, subject, object, emotion:"
encoder_prompt: "[EOS]Summary of the above text. Topic, speaker, subject, object, emotion:"
lm_loss_natural_prefix: "[EOS]Short explanation of something. Topic, speaker, subject, object, emotion:"  # Natural language prefix for base model in LM loss

# Trainable components - FROZEN base model
trainable_components:
  decoder:
    base_model: false                 # FROZEN throughout
    projection_layer: true            # Train projection
    eye_init: true
    output_head: false                # Keep LM head frozen too
    use_flash_attention: false
  encoder:
    base_model: false                 # FROZEN throughout
    use_base_model: true
    projection_layer: true            # Train projection
    eye_init: true
    output_layer: 4
    soft_prompt_init_text: ${encoder_prompt}

alpha_schedule: 
  type: "constant"
  value: 1.0

num_train_epochs: 20                   # 2 epochs should be plenty for OpenWebText

learning_rate: 1.0e-3
# Learning rate scheduler
lr_scheduler:
  type: "cosine"                      # Cosine annealing works well
  warmup_steps: 10                  # Number of *optimizer steps* for warmup.
                                    # Total micro-steps for warmup = warmup_steps * gradient_accumulation_steps.
                                    # E.g., 10 optimizer steps * 32 accum steps = 320 micro-steps for warmup.
  warmup_start_factor: 0.1            # Start at 10% of target LR
  eta_min: 1.0e-5   

batch_size: 2048
gradient_accumulation_steps: 1
gumbel_tau_schedule:
  constant_steps_before_linear_decay: 1000

# WandB configuration
wandb:
  project: "consistency-lens-simplestories"
  mode: "online"